### ISSUE TITLE
MSH Flag parsing issues

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#188]
## Problem 1: Throws a error because of wrong logic.
```txt
If you start msh with default config but start parameters for folder and file you get the error
loadDefault: getVersionInfo: open {path\to\server\folder}\{server.jar}: The system cannot find the path specified. [03f101]
It will still work as usual. Still this should be avoided to not confuce users.
```

----

## Problem 2: Bad parsing...

This is more complicated and mainly affects the pterodactyl egg becace the " are impossible to create. See my ptero help for that below
You can also replicate it on windows.
It first seems like it works because flags dosn´t add a tail ( flag.Args() ) but when MSH tryes to execute ms
```ps
go run minecraft-server-hibernation.go -d=3 -folder ./ -file "paper-1.19.3 359.jar"
...
[info ≡≡≡ ] MINECRAFT SERVER IS STARTING!
[serv ≡≡  ] Error: Unable to access jarfile paper-1.19.3
[info ≡≡≡ ] MINECRAFT SERVER IS OFFLINE!
```
gets written. Indicating that it failed to parse at the [SPACE] 

### Case 1:
In the documentaion of flags its sugested to use = in such cases.
```ps
go run minecraft-server-hibernation.go -d=3 -folder=./ -file="paper-1.19.3 359.jar"
```
_This now fails completly. Lets have a look.
The folder variable is just an emty string...
The file variable is its default value
And the tail contains our parameter [./ -p2=paper-1.19.3 359.jar]_

### Case 2:
Now lets also add " to our folder.
```ps
go run minecraft-server-hibernation.go -d=3 -folder="./" -file="paper-1.19.3 359.jar"
```
_Flags output looks fine
Folder: ./
File: paper-1.19.3 359.jar
tail: []_

But msh still trys to execute the wrong file?
```ps
[info ≡≡≡ ] MINECRAFT SERVER IS STARTING!
[serv ≡≡  ] Error: Unable to access jarfile paper-1.19.3
[info ≡≡≡ ] MINECRAFT SERVER IS OFFLINE!
```

----

### Pterodactyl Discord Question i explained the case and ask for help

```sh
# What i tryed, and the output:
./main.bin -p1= \"Hello World \" -p2=Marc
# p1: "Hello
# p2: bar
# tail: [World -p2=Marc]

./main.bin -p1="Hello World" -p2=Marc
# p1:Hello%20World
# p2: Marc
# tail: []

./main.bin $(echo '-p1="') Hello World$(echo '"') -p2=Marc
# p1: "Hello
# p2: bar
# tail: [World -p2=Marc]

# On windows(PS/CMD) and linux (BASH) it works.
./main.bin -p1="Hello World" -p2=Marc
# p1: Hello World
# p2: Marc
# tail: []
```

### Expected Behavior

Solution 1:
```txt
Msh enters LoadConfig() as one of its first steps.
This will execute loadDefault()
Within the loadDefault() function it tryes to read the version of ms
With this line version, protocol, logMsh := c.getVersionInfo()
But at this point, we havent processed start parameters because those are loaded in loadRuntime() and thats ran after loadDefault() completion
```

Problem 2:
It shuld parse arguments with spaces no matter the used shell.

### Steps to Reproduce

All described in the behavior box.

### MSH-Version

2.4.10

### Operating system

Ubuntu 21 & Windows

### Minecraft Version

1.19.2

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
### problem 1
- fixed in d272d3e08a0d67dc7fd3b1734bb029811c05a6cb

**Comment by gekigek99** [comment]
> go run minecraft-server-hibernation.go -d=3 -folder ./ -file "paper-1.19.3 359.jar"

running on windows:

```
PS > .\msh.exe -d=3 -folder "C:\Users\Administrator\Desktop\minecraft server" -file "paper-1.19.3 359.jar"
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.10               ║
║ |_| |_| |_|___/_| |_| -------               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/12/26 19:19:27 [info  ≡   ] checking OS support...
2022/12/26 19:19:28 [info  ≡   ] loading config...
2022/12/26 19:19:28 [info  ≡   ] reading config file: "C:\Users\Administrator\Desktop\Administrator\informatica\programmazione\» Go\minecraft-server-hibernation\msh\msh-config.json"
2022/12/26 19:19:28 [info  ≡   ] msh instance file exists
2022/12/26 19:19:28 [info  ≡   ] msh instance loaded is healthy
2022/12/26 19:19:28 [info  ≡≡≡≡] setting log level to: 3
2022/12/26 19:19:28 [info  ≡≡≡ ] eula.txt exist and is set to true
2022/12/26 19:19:28 [info  ≡   ] msh proxy setup: 0.0.0.0:25555 --> 127.0.0.1:25565
2022/12/26 19:19:28 [info  ≡   ] sending api2 request
2022/12/26 19:19:28 [info  ≡   ] segment reset
2022/12/26 19:19:28 [info  ≡≡≡ ] listening for new clients to connect on 0.0.0.0:25555 ...
2022/12/26 19:19:28 [info  ≡   ] reading api2 response
2022/12/26 19:19:28 [warn  ≡≡≡≡] sgmMgr: msh (v2.4.10) is running a dev release [01f000]
```

```
PS > .\msh.exe -d=3 -folder=C:\Users\Administrator\Desktop\minecraftserver -file="paper-1.19.3 359.jar" 
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.10               ║
║ |_| |_| |_|___/_| |_| -------               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/12/26 19:23:25 [info  ≡   ] checking OS support...
2022/12/26 19:23:25 [info  ≡   ] loading config...
2022/12/26 19:23:25 [info  ≡   ] reading config file: "C:\Users\Administrator\Desktop\Administrator\informatica\programmazione\» Go\minecraft-server-hibernation\msh\msh-config.json"
2022/12/26 19:23:25 [info  ≡   ] msh instance file exists
2022/12/26 19:23:25 [info  ≡   ] msh instance loaded is healthy
2022/12/26 19:23:25 [info  ≡≡≡≡] setting log level to: 3
2022/12/26 19:23:25 [info  ≡≡≡ ] eula.txt exist and is set to true
2022/12/26 19:23:25 [info  ≡   ] msh proxy setup: 0.0.0.0:25555 --> 127.0.0.1:25565
2022/12/26 19:23:25 [info  ≡   ] sending api2 request
2022/12/26 19:23:25 [info  ≡   ] segment reset
2022/12/26 19:23:25 [info  ≡≡≡ ] listening for new clients to connect on 0.0.0.0:25555 ...
2022/12/26 19:23:25 [info  ≡   ] reading api2 response
2022/12/26 19:23:25 [warn  ≡≡≡≡] sgmMgr: msh (v2.4.10) is running a dev release [01f000]
```

```
PS > .\msh.exe -d=3 -folder="C:\Users\Administrator\Desktop\minecraft server" -file="paper-1.19.3 359.jar"
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.10               ║
║ |_| |_| |_|___/_| |_| -------               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/12/26 19:21:21 [info  ≡   ] checking OS support...
2022/12/26 19:21:21 [info  ≡   ] loading config...
2022/12/26 19:21:21 [info  ≡   ] reading config file: "C:\Users\Administrator\Desktop\Administrator\informatica\programmazione\» Go\minecraft-server-hibernation\msh\msh-config.json"
2022/12/26 19:21:21 [info  ≡   ] msh instance file exists
2022/12/26 19:21:21 [info  ≡   ] msh instance loaded is healthy
2022/12/26 19:21:21 [info  ≡≡≡≡] setting log level to: 3
2022/12/26 19:21:21 [info  ≡≡≡ ] eula.txt exist and is set to true
2022/12/26 19:21:21 [info  ≡   ] msh proxy setup: 0.0.0.0:25555 --> 127.0.0.1:25565
2022/12/26 19:21:21 [info  ≡   ] sending api2 request
2022/12/26 19:21:22 [info  ≡   ] segment reset
2022/12/26 19:21:22 [info  ≡≡≡ ] listening for new clients to connect on 0.0.0.0:25555 ...
2022/12/26 19:21:22 [info  ≡   ] reading api2 response
2022/12/26 19:21:22 [warn  ≡≡≡≡] sgmMgr: msh (v2.4.10) is running a dev release [01f000]
```

_I really can't reproduce the bug_

---

idk what about adding a replace function to replace `[space]` to `" "` so that in egg config you can write `[space]`?

**Comment by BolverBlitz** [comment]
In nither of your shared logs you tryed to start ms or added extra flags logging like i did. 
Please type `ms start` to see the error

**Comment by gekigek99** [comment]
what extra flags do I have to add?

**Comment by gekigek99** [comment]
> Please type ms start to see the error

ah ops lol

**Comment by BolverBlitz** [comment]
> what extra flags do I have to add?

Not adding extra flags, i wrote `extra flags logging`

https://github.com/gekware/minecraft-server-hibernation/blob/bff5cf046f2ea334385e58982e681077d57513e5/lib/config/config.go#L177-L184
```GO
fmt.Println("Folder:", *c.Server.Folder)
fmt.Println("File:", *c.Server.FileName)
fmt.Println("tail:", flag.Args())
```
https://github.com/gekware/minecraft-server-hibernation/blob/bff5cf046f2ea334385e58982e681077d57513e5/lib/config/config.go#L186-L190

**Comment by gekigek99** [comment]
### Problem 2
fixed in 6398dd90623902ee34a33a5660f969f5a20e8a90

_@BolverBlitz  can you check?_

**Comment by BolverBlitz** [comment]
It does solve the example i made here, would you be able do build linux x86 for me. I´m not in a place where i can do it rn.
Because the main reason i opend the issue still is `This is more complicated and mainly affects the pterodactyl egg becace the " are impossible to create.` and i can´t see any attemt this got fixed ^^

**Comment by gekigek99** [comment]
here you go: [msh-v2.4.10-6398dd9.zip](https://github.com/gekware/minecraft-server-hibernation/files/10305103/msh-v2.4.10-6398dd9.zip)

**Comment by BolverBlitz** [comment]
Thank you. Yeah as i expected.
```sh
container@pterodactyl~ ./msh_server.bin -port 10037 -d 3 -file server.jar -allowkill 30 -timeout 120 -SuspendRefresh 30 -wlimport -SuspendAllow -msparam "-Xms128M -Xmx2354M"
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.10               ║
║ |_| |_| |_|___/_| |_| 6398dd9               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/12/27 01:39:19 [info  ≡   ] checking OS support...
2022/12/27 01:39:19 [info  ≡   ] loading config...
2022/12/27 01:39:19 [info  ≡   ] reading config file: "/home/container/msh-config.json"
2022/12/27 01:39:19 [info  ≡   ] msh instance file exists
2022/12/27 01:39:19 [error ≡   ] okV0: machineid: machineid: open /etc/machine-id: no such file or directory [03f003]
2022/12/27 01:39:19 [info  ≡   ] msh instance loaded is healthy
flag provided but not defined: -Xmx2354M"
......
```

I tryed and you fixed the windows example i toled you, but MSH still parses arguments incorectly for the egg...

**Comment by BolverBlitz** [comment]
I thought the windows bug i found was the same, looking at your fix i see now it wasn´t. Just happend to have the same result.
Sorry for that. At least thats fixed now. Egg still dosn´t work :/
Affected: Hib Message, Start Message and the memory start command (as seen in my example)

**Comment by gekigek99** [comment]
> I tryed and you fixed the windows example i toled you, but MSH still parses arguments incorectly for the egg...

I think that ptero has kinda the same issue with spaces that msh parsing had.

**Comment by BolverBlitz** [comment]
> I think that ptero has kinda the same issue with spaces that msh parsing had.

Well. Looking at other eggs, other applications have no problem with this at all. 
![grafik](https://user-images.githubusercontent.com/35345288/209596330-73121637-bc56-4e8b-b94b-addaa64595e6.png)

**Comment by gekigek99** [comment]
ok can you tell me a simple example command to use as a debug test?
maybe even setup an egg just for it so I can test on that

**Comment by BolverBlitz** [comment]
> ok can you tell me a simple example command to use as a debug test?

https://panel.ebg.pw/server/d5528abf
How to use: 
1: Delete old msh_server.bin 
2: Upload new msh_server.bin (Needs to be Linux x86(_64)
3: Click on "Settings" click on "Reinsall Server
4: Start the Server, will be running your uploaded Binary

> maybe even setup an egg just for it so I can test on that

Added a debug egg here.
https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/commit/3d87d3d28886ad480b6e97cf7e21100f40ce5224

> what does -batchmode do?

Tells the server to run without a GUI

**Comment by BolverBlitz** [comment]
I found 2 alternative ways to parse arguments.
 https://github.com/spf13/cobra
 https://github.com/jessevdk/go-flags
 
Example using  https://github.com/jessevdk/go-flags
go.mod
```txt
module clitester

go 1.19

require (
	github.com/jessevdk/go-flags v1.5.0 // indirect
	golang.org/x/sys v0.0.0-20210320140829-1e4c9ba3b0c4 // indirect
)
```
main.go
```go
package main

import (
	"fmt"
	"os"

	"github.com/jessevdk/go-flags"
)


type Optionen struct {
	Username string `short:"u" long:"username" description:"Username"`
}

func main() {
	var opt Optionen
	_, err := flags.Parse(&opt)
	if err != nil {
		os.Exit(1)
	}
	fmt.Println(opt.Username)
}
```

As MSH currently does, it works on windows. Escaped chars \" on windows work kinda... Ver ystrange

On Pterodactyl:
Ptero command: ./msh_server.bin -u=\"-Xms128M -Xmx{{SERVER_MEMORY}}M\"
In Shell:
./msh_server.bin -u="-Xms128M -Xmx4096M"
invalid argument for flag `-u, --username' (expected string): invalid syntax

**Comment by gekigek99** [comment]
> Added a debug egg here.
> https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/commit/3d87d3d28886ad480b6e97cf7e21100f40ce5224

can you add a modifiable variable `-msparam` and `-infoHibe` so I can play around with them?

**Comment by gekigek99** [comment]
on the [test egg](https://panel.ebg.pw/server/d5528abf) I demostrated that even with a bash executable the arguments are splitted by a space... this should indicate that it's the internal ptero terminal that it's passing the wrongly splitted parameters.

```
./msh_server.bin -port 10039 -d 3 -file 'ser ver.jar' -allowkill 30 -timeout 120 -SuspendRefresh 30 -wlimport -SuspendAllow -msparam "-Xms128M -Xmx4096M"
-port|10039|-d|3|-file|'ser|ver.jar'|-allowkill|30|-timeout|120|-SuspendRefresh|30|-wlimport|-SuspendAllow|-msparam|"-Xms128M|-Xmx4096M"|
```

I could manually create a parser to unify the spitted parameters `|'ser|ver.jar'|` and `|"-Xms128M|-Xmx4096M"|` but I would really prefer to use less "handmade" solutions...

**Comment by BolverBlitz** [comment]
> can you add a modifiable variable -msparam and -infoHibe so I can play around with them?

No, variables are not parsed the same. I made it so its \" as all other eggs do it and its also kinda standart.

**Comment by gekigek99** [comment]
asked a question [here](https://github.com/pterodactyl/panel/issues/4641)

**Comment by gekigek99** [comment]
removing the label `2.5.0 update` from the issue as it's not related to msh itself

@BolverBlitz

**Comment by gekigek99** [comment]
fixed in d2daf2a1112e21dc0bfb12e52d9afea473782a90
